// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	feedback "github.com/GP-3-Kelompok-2/airbnb-app-project/features/feedback"
	mock "github.com/stretchr/testify/mock"
)

// FeedbackRepository is an autogenerated mock type for the RepositoryInterface type
type FeedbackRepository struct {
	mock.Mock
}

// CreateFeedback provides a mock function with given fields: input
func (_m *FeedbackRepository) CreateFeedback(input feedback.FeedbackCore) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(feedback.FeedbackCore) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFeedbackRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewFeedbackRepository creates a new instance of FeedbackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFeedbackRepository(t mockConstructorTestingTNewFeedbackRepository) *FeedbackRepository {
	mock := &FeedbackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
